/**
 * CyberReportHub API
 * The API to interact with CyberReportHub
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JsonIocResponse } from './jsonIocResponse';
import { JsonStatsResponse } from './jsonStatsResponse';

export interface SearchReportDetailsResponse {
  reportId: number;
  reportType: string;
  generatedDate: string;
  lastModified: string;
  emailStatus: boolean;
  /**
   * List of article titles in the report
   */
  articleTitles: Array<string>;
  iocs: Array<JsonIocResponse>;
  stats: Array<JsonStatsResponse>;
}
